# Fabric Properties
# check these on https://modmuss50.me/fabric.html
    minecraft_dependency=26.1
    minecraft_version=26.1
    fabric_api_version=0.144.4+26.1
    game_versions=26.1

# Mod Dependencies
    modmenu_version=18.0.0-alpha.8
    malilib_version=0.28.1
    tweakeroo_version=0.28.0
    tweakermore_version=v3.30.0-mc1.21.11
    itemscroller_version=QT3ZdOmj
    litematica_version=0.27.0
    syncmatica_version=5Gz2beaq
