# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_dependency=26.1.x
minecraft_version=26.1.2
fabric_api_version=0.155.2+26.1.2
game_versions=26.1\n26.1.1\n26.1.2

# Mod Dependencies
modmenu_version=18.0.0
malilib_version=0.28.11
tweakeroo_version=0.28.8
tweakermore_version=v3.33.2-mc26.1.2
itemscroller_version=0.31.5
litematica_version=0.27.12
syncmatica_version=wsFbuMkX

