# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_dependency=1.21.11
minecraft_version=1.21.11
fabric_api_version=0.141.6+1.21.11
game_versions=1.21.11

# Mod Dependencies
modmenu_version=17.0.1-beta.1
malilib_version=0.27.19
tweakeroo_version=0.27.13
tweakermore_version=v3.33.2-mc1.21.11
itemscroller_version=0.30.6
litematica_version=0.26.14
syncmatica_version=jMRygmU0

