# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_dependency=1.21.11
minecraft_version=1.21.11
fabric_api_version=0.141.4+1.21.11
game_versions=1.21.11

# Mod Dependencies
modmenu_version=17.0.0
malilib_version=0.27.12
tweakeroo_version=0.27.9
tweakermore_version=v3.31.0-mc1.21.11
itemscroller_version=0.30.5
litematica_version=0.26.8
syncmatica_version=q8q5Xv6K
yacl_version=3.8.2+1.21.11-fabric
