# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_dependency=>=26.2
minecraft_version=26.2
fabric_api_version=0.159.0+26.2
game_versions=26.2

# Mod Dependencies
modmenu_version=20.0.1
malilib_version=0.29.5
tweakeroo_version=0.29.4
tweakermore_version=v3.33.2-mc26.2
itemscroller_version=0.32.1
litematica_version=0.28.6
syncmatica_version=POv0nHxV
