# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_dependency=>=26.1
minecraft_version=26.1.1
fabric_api_version=0.150.0+26.1.2
game_versions=26.1\n26.1.1

# Mod Dependencies
modmenu_version=18.0.0-beta.1
malilib_version=0.28.6
tweakeroo_version=0.28.4
tweakermore_version=v3.31.0-mc26.1.2
itemscroller_version=0.31.4
litematica_version=0.27.6
syncmatica_version=hiDPXGGO
yacl_version=3.9.4+26.1-fabric
